import current from './router16';
import type { Env } from './index';

type Row=unknown[];
type H={name?:string;value?:string};
type Msg={id?:string;threadId?:string;labelIds?:string[];snippet?:string;internalDate?:string;payload?:{headers?:H[]}};
const VALID_BUDGETS=new Set(['عائلي شهري','عائلي سنوي','شخصي شهري','شخصي سنوي','تأمين المصروف','تأمين الدخل','الادخار والاستثمار']);
function cors(env:Env){return{'Access-Control-Allow-Origin':env.FRONTEND_ORIGIN||'https://m14901507-boop.github.io','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Credentials':'true','Vary':'Origin'};}
function json(x:unknown,env:Env,s=200){return Response.json(x,{status:s,headers:cors(env)});}
function txt(v:unknown){return String(v??'').trim();}
function hv(m:Msg,n:string){return(m.payload?.headers||[]).find(x=>(x.name||'').toLowerCase()===n.toLowerCase())?.value||'';}
async function auth(req:Request,env:Env){const u=new URL(req.url);u.pathname='/auth/status';const r=await current.fetch(new Request(u.toString(),{headers:req.headers}),env);const d:any=await r.json().catch(()=>({}));return !!d?.authenticated;}
async function token(env:Env){const b=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID.trim(),client_secret:env.GOOGLE_CLIENT_SECRET.trim(),refresh_token:env.GOOGLE_REFRESH_TOKEN.trim(),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b});const d:any=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth ${r.status}`);return String(d.access_token);}
async function gj(url:string,t:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${t}`,Accept:'application/json',...(init.headers||{})}});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);return d;}
async function read(env:Env,t:string,name:string,range:string){const rg=encodeURIComponent(`'${name}'!${range}`);const d:any=await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`,t);const v:Row[]=d.values||[];return{headers:v[0]||[],rows:v.slice(1)};}
async function batch(env:Env,t:string,data:Array<{range:string;values:unknown[][]}>){if(!data.length)return;await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values:batchUpdate`,t,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({valueInputOption:'USER_ENTERED',data})});}
async function append(env:Env,t:string,rows:Row[]){if(!rows.length)return;const rg=encodeURIComponent("'العمليات'!A:O");await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,t,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values:rows})});}
function isNonFinancial(g:Row){return /غير\s*مالي|أمان|الامان|تسجيل\s*الدخول/i.test([g[1],g[2],g[3],g[4]].map(txt).join(' '));}
function usableGuide(g:Row){if(!txt(g[0])||!txt(g[6])||isNonFinancial(g))return false;return /مصروف|دخل|تحويل\s*داخلي|وارد|صادر|شراء|سحب/i.test([g[1],g[3],g[4]].map(txt).join(' '));}
function applyGuide(op:Row,g:Row,status='متزامن'){const r=[...op];while(r.length<15)r.push('');r[2]=txt(g[0]);r[3]=VALID_BUDGETS.has(txt(g[1]))?txt(g[1]):'';r[6]=txt(g[3])||r[6];r[9]=txt(g[2]);r[10]=status;r[12]=txt(g[9]);r[13]=txt(g[10]);r[14]=txt(g[11]);return r;}
function clearGuide(op:Row,status='بدون تصنيف بند'){const r=[...op];while(r.length<15)r.push('');r[2]='';r[3]='';r[9]='';r[10]=status;r[12]='';r[13]='';r[14]='';return r;}
function bank(text:string){const s=text.toLowerCase();if(/ahli|الأهلي|الاهلي/.test(s))return'بنك الأهلي';if(/meethaq|ميثاق/.test(s))return'ميثاق';if(/dhofar|ظفار/.test(s))return'بنك ظفار';if(/sohar|صحار/.test(s))return'بنك صحار';return'';}
function account(text:string,b:string){if(/0108\s*[#*xX]{4,}\s*001\b/i.test(text))return'001';if(/0108\s*[#*xX]{4,}\s*002\b/i.test(text))return'002';const m=text.match(/[#*xX]{2,}(\d{1,4})\b/);let n=m?.[1]||'';if(b==='ميثاق'&&['21','021','0021'].includes(n))n='0021';if(b==='ميثاق'&&['22','022','0022'].includes(n))n='0022';return n;}
function amount(text:string){for(const p of[/(?:OMR|RO|O\.?R\.?)\s*([0-9][0-9,]*(?:\.[0-9]{1,3})?)/i,/([0-9][0-9,]*(?:\.[0-9]{1,3})?)\s*(?:OMR|RO|O\.?R\.?)/i]){const m=text.match(p);if(m?.[1])return Number(m[1].replace(/,/g,''));}return null;}
function opType(text:string){if(/POS Purchase|purchase/i.test(text))return'مصروف';if(/\bcredited\b/i.test(text))return'دخل';if(/\bdebited\b/i.test(text))return'مصروف';if(/withdrawal|ATM/i.test(text))return'مصروف';return'';}
function buildNew(g:Row,m:Msg){const from=hv(m,'From'),subject=hv(m,'Subject'),snippet=txt(m.snippet),text=`${from}\n${subject}\n${snippet}`,b=bank(text),a=account(text,b),amt=amount(text),raw=hv(m,'Date')||(m.internalDate?new Date(Number(m.internalDate)).toISOString():new Date().toISOString()),d=new Date(raw),date=Number.isFinite(d.getTime())?d.toISOString():raw,move=txt(g[3])||opType(text);return[m.id||'',date,txt(g[0]),VALID_BUDGETS.has(txt(g[1]))?txt(g[1]):'',amt??'',subject||snippet.slice(0,240),move,opType(text),[b,a].filter(Boolean).join(' '),txt(g[2]),'متزامن مع Gmail',new Date().toISOString(),txt(g[9]),txt(g[10]),txt(g[11])];}
async function getMsg(t:string,id:string){return gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`,t) as Promise<Msg>;}
async function saveItem(env:Env,p:any){const row=Number(p?.row);if(!Number.isInteger(row)||row<2)throw new Error('رقم صف البند غير صالح');const ch=p?.changes||{},budget=txt(ch.legacyClassification),category=txt(ch.category),period=txt(ch.period),scope=txt(ch.scope);if(budget&&!VALID_BUDGETS.has(budget))throw new Error('نوع الموازنة غير صالح');const t=await token(env),before=await read(env,t,'دليل البنود','A:L'),old=before.rows[row-2]||[],oldName=txt(old[0]);await batch(env,t,[{range:`'دليل البنود'!B${row}`,values:[[budget]]},{range:`'دليل البنود'!J${row}:L${row}`,values:[[category,period,scope]]}]);const after=await read(env,t,'دليل البنود','A:L'),g=after.rows[row-2]||[];if(txt(g[1])!==budget)throw new Error('لم يتم تثبيت الموازنة في Google Sheets');const ops=await read(env,t,'العمليات','A:O'),writes:Array<{range:string;values:unknown[][]}>=[];let propagated=0;ops.rows.forEach((r,i)=>{if(txt(r[2])!==oldName)return;const out=applyGuide(r,g,'متزامن بعد حفظ البند');writes.push({range:`'العمليات'!A${i+2}:O${i+2}`,values:[out]});propagated++;});await batch(env,t,writes);return{ok:true,row,item:txt(g[0]),budget:txt(g[1]),propagated};}
async function sync(env:Env,since:string,full:boolean){const t=await token(env),guide=await read(env,t,'دليل البنود','A:L'),ops=await read(env,t,'العمليات','A:O');const byLabel=new Map<string,Row>(),byName=new Map<string,Row>();for(const g of guide.rows){if(txt(g[0]))byName.set(txt(g[0]),g);if(usableGuide(g))byLabel.set(txt(g[6]),g);}const byId=new Map<string,{r:Row,n:number}>();ops.rows.forEach((r,i)=>{const id=txt(r[0]);if(id)byId.set(id,{r,n:i+2});});const guideWrites:Array<{range:string;values:unknown[][]}>=[];let guideUpdated=0;ops.rows.forEach((r,i)=>{const item=txt(r[2]);if(!item)return;const g=byName.get(item);if(!g)return;const out=applyGuide(r,g,'متزامن مع دليل البنود');if(JSON.stringify(out)!==JSON.stringify(r.slice(0,15))){guideWrites.push({range:`'العمليات'!A${i+2}:O${i+2}`,values:[out]});guideUpdated++;}});await batch(env,t,guideWrites);
 const profile:any=await gj('https://gmail.googleapis.com/gmail/v1/users/me/profile',t);const currentHistory=txt(profile.historyId);const ids:string[]=[];
 if(since&&!full){try{const h:any=await gj(`https://gmail.googleapis.com/gmail/v1/users/me/history?startHistoryId=${encodeURIComponent(since)}&maxResults=50&historyTypes=labelAdded&historyTypes=labelRemoved`,t);for(const x of h.history||[]){for(const a of x.labelsAdded||[])if(a.message?.id)ids.push(txt(a.message.id));for(const a of x.labelsRemoved||[])if(a.message?.id)ids.push(txt(a.message.id));}}catch{}}
 if(full||!since){const l:any=await gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent('has:userlabels newer_than:30d')}&maxResults=20`,t);for(const x of l.messages||[])if(x.id)ids.push(txt(x.id));}
 // أولوية لاستعادة السجلات التي فقدت بندها/تصنيفها سابقًا.
 for(const r of ops.rows){if(ids.length>=16)break;if(txt(r[0])&&(!txt(r[2])||!txt(r[3])))ids.push(txt(r[0]));}
 const unique=[...new Set(ids)].slice(0,16),writes:Array<{range:string;values:unknown[][]}>=[],adds:Row[]=[];let updated=0,added=0,cleared=0,ambiguous=0;
 for(const id of unique){const m=await getMsg(t,id),matched=(m.labelIds||[]).map(l=>byLabel.get(l)).filter(Boolean) as Row[],ex=byId.get(id);if(matched.length===1){if(ex){const out=applyGuide(ex.r,matched[0],'متزامن مع Gmail');if(JSON.stringify(out)!==JSON.stringify(ex.r.slice(0,15))){writes.push({range:`'العمليات'!A${ex.n}:O${ex.n}`,values:[out]});updated++;}}else{adds.push(buildNew(matched[0],m));added++;}}else if(matched.length===0&&ex){const out=clearGuide(ex.r,'أزيل تصنيف البند من Gmail');if(JSON.stringify(out)!==JSON.stringify(ex.r.slice(0,15))){writes.push({range:`'العمليات'!A${ex.n}:O${ex.n}`,values:[out]});cleared++;}}else if(matched.length>1)ambiguous++;}
 await batch(env,t,writes);await append(env,t,adds);return{ok:true,historyId:currentHistory,checked:unique.length,added,updated,cleared,ambiguous,guideUpdated};}
export default{async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url);if(request.method==='OPTIONS')return current.fetch(request,env);try{if(u.pathname==='/api/items/save'&&request.method==='POST'){if(!(await auth(request,env)))return json({ok:false,error:'Unauthorized'},env,401);return json(await saveItem(env,await request.json()),env);}if(u.pathname==='/api/sync/operations'&&request.method==='POST'){if(!(await auth(request,env)))return json({ok:false,error:'Unauthorized'},env,401);return json(await sync(env,txt(u.searchParams.get('since')),u.searchParams.get('full')==='1'),env);}return current.fetch(request,env);}catch(e:any){return json({ok:false,error:e?.message||String(e)},env,500);}}};