import base, { type Env } from './index';

type Row = unknown[];
type GmailHeader={name?:string;value?:string};
type GmailMessage={id?:string;snippet?:string;internalDate?:string;labelIds?:string[];payload?:{headers?:GmailHeader[]}};

function clean(v:unknown){return String(v??'').trim().toLowerCase().replace(/[\s_\-]+/g,'');}
function headerIndex(headers:unknown[],patterns:RegExp[]){for(let i=0;i<headers.length;i++){const x=clean(headers[i]);if(patterns.some(p=>p.test(x)))return i;}return-1;}
function colName(index:number){let n=index+1,s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
function headerValue(m:GmailMessage,name:string){return(m.payload?.headers||[]).find(x=>(x.name||'').toLowerCase()===name.toLowerCase())?.value||'';}
function cors(env:Env){return{'Access-Control-Allow-Origin':env.FRONTEND_ORIGIN||'https://m14901507-boop.github.io','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'};}

function detectBankName(text:string){const low=text.toLowerCase();if(/ahli|الأهلي|الاهلي/.test(low))return'بنك الأهلي';if(/meethaq|ميثاق/.test(low))return'ميثاق';if(/dhofar|ظفار/.test(low))return'بنك ظفار';if(/sohar|صحار/.test(low))return'بنك صحار';if(/nizwa|نزوى/.test(low))return'بنك نزوى';if(/bank muscat|bankmuscat|بنك مسقط/.test(low))return'بنك مسقط';if(/oman arab bank|\boab\b|عمان العربي/.test(low))return'بنك عمان العربي';if(/national bank of oman|\bnbo\b|الوطني العماني/.test(low))return'البنك الوطني العماني';if(/alizz|العز/.test(low))return'بنك العز الإسلامي';return'';}
function normalizeAccount(bank:string,no:string){let n=String(no||'').replace(/\D/g,'');if(bank==='بنك الأهلي'){if(['1','01','001'].includes(n))return'001';if(['2','02','002'].includes(n))return'002';return'';}if(bank==='ميثاق'&&['21','021','0021'].includes(n))return'0021';return n;}
function extractAccountNumber(text:string,bank=''){if(/0108\s*[#*xX]{4,}\s*001\b/i.test(text))return'001';if(/0108\s*[#*xX]{4,}\s*002\b/i.test(text))return'002';const candidates:string[]=[];for(const p of[/(?:account|acct|a\/?c)(?:\s*(?:no|number|ending|ending\s+in))?[^0-9#*xX]{0,24}[#*xX-]*(\d{1,4})\b/ig,/[#*xX]{2,}(\d{1,4})\b/g,/\b\d{2,8}[#*xX-]{2,}(\d{1,4})\b/g]){let m:RegExpExecArray|null;while((m=p.exec(text))!==null)if(m[1])candidates.push(m[1]);}return normalizeAccount(bank,candidates[0]||'');}
function extractAmount(text:string){for(const p of[/(?:OMR|RO|O\.?R\.?)\s*([0-9][0-9,]*(?:\.[0-9]{1,3})?)/i,/([0-9][0-9,]*(?:\.[0-9]{1,3})?)\s*(?:OMR|RO|O\.?R\.?)/i]){const m=text.match(p);if(m?.[1])return Number(m[1].replace(/,/g,''));}return null;}
function detectOperationType(text:string){if(/POS Purchase|Debit Card.*utili[sz]ed|purchase/i.test(text))return'مصروف/شراء بالبطاقة';if(/\bcredited\b/i.test(text))return'دخل/تحويل وارد';if(/\bdebited\b/i.test(text))return'مصروف/تحويل صادر';if(/\b(withdrawal|withdrawn|ATM)\b/i.test(text))return'مصروف/سحب نقدي';return'غير محدد';}
function simpleMovement(v:string){if(/دخل|وارد|credited/i.test(v))return'دخل';if(/مصروف|صادر|debited|purchase|withdraw/i.test(v))return'مصروف';if(/تحويل/i.test(v))return'تحويل';return v||'غير محدد';}
function currentAccountIsComplete(text:string){const bank=detectBankName(text);if(!bank)return false;const m=text.match(/(?:حساب|account|acct|_|-|\s)(\d{1,4})\s*$/i);return Boolean(normalizeAccount(bank,m?.[1]||''));}
function guideBudget(r:Row){const explicit=String(r[1]||'').trim(),known=['عائلي شهري','عائلي سنوي','شخصي شهري','شخصي سنوي','تأمين المصروف','تأمين الدخل','الادخار والاستثمار'];if(known.includes(explicit))return explicit;const period=String(r[10]||''),scope=String(r[11]||'');if(scope.includes('عائلي')&&period.includes('شهري'))return'عائلي شهري';if(scope.includes('عائلي')&&period.includes('سنوي'))return'عائلي سنوي';if(scope.includes('شخصي')&&period.includes('شهري'))return'شخصي شهري';if(scope.includes('شخصي')&&period.includes('سنوي'))return'شخصي سنوي';return explicit||'غير مصنف';}

async function accessToken(env:Env){const body=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID.trim(),client_secret:env.GOOGLE_CLIENT_SECRET.trim(),refresh_token:env.GOOGLE_REFRESH_TOKEN.trim(),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d:any=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth ${r.status}`);return String(d.access_token);}
async function googleJson(url:string,token:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${token}`,Accept:'application/json',...(init.headers||{})}});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);return d;}
async function readSheet(env:Env,token:string,sheet:string,rangePart:string){const range=encodeURIComponent(`'${sheet}'!${rangePart}`),url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${range}?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`,d=await googleJson(url,token),v:Row[]=d.values||[];return{headers:v[0]||[],rows:v.slice(1)};}
async function readOperations(env:Env,token:string){return readSheet(env,token,'العمليات','A:O');}
async function operationResponse(env:Env){const token=await accessToken(env),ops=await readOperations(env,token);return{ok:true,sheet:'العمليات',headers:ops.headers,rows:ops.rows,sheetRowCount:ops.rows.length,liveCount:0,rowCount:ops.rows.length};}
async function appendOperationRows(env:Env,token:string,rows:Row[]){if(!rows.length)return;const range=encodeURIComponent("'العمليات'!A:O"),url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${range}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`;await googleJson(url,token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values:rows})});}
async function gmailListByLabel(token:string,labelId:string,maxResults:number){return googleJson(`https://gmail.googleapis.com/gmail/v1/users/me/messages?labelIds=${encodeURIComponent(labelId)}&maxResults=${maxResults}`,token);}
async function gmailMessage(token:string,id:string){return googleJson(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`,token) as Promise<GmailMessage>;}
async function updateGuideSync(env:Env,token:string,rowNumbers:number[]){if(!rowNumbers.length)return;const stamp=new Date().toISOString(),data=rowNumbers.flatMap(row=>[{range:`'دليل البنود'!H${row}`,values:[['تمت المزامنة']]},{range:`'دليل البنود'!I${row}`,values:[[stamp]]}]);await googleJson(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values:batchUpdate`,token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({valueInputOption:'USER_ENTERED',data})});}
function buildOperationRow(headers:Row,g:Row,m:GmailMessage){const from=headerValue(m,'From'),subject=headerValue(m,'Subject'),snippet=(m.snippet||'').replace(/\s+/g,' ').trim(),combined=`${from}\n${subject}\n${snippet}`,bank=detectBankName(combined),account=extractAccountNumber(combined,bank),amount=extractAmount(combined),rawDate=headerValue(m,'Date')||(m.internalDate?new Date(Number(m.internalDate)).toISOString():new Date().toISOString()),parsedDate=new Date(rawDate),date=!isNaN(parsedDate.getTime())?parsedDate.toISOString():rawDate,detected=detectOperationType(combined),movement=simpleMovement(String(g[3]||'').trim()||detected),status=(bank&&account&&amount!=null)?'مسجل تلقائيا من Gmail':'يحتاج مراجعة',row=new Array(15).fill('');const put=(patterns:RegExp[],fallback:number,value:unknown)=>{const i=headerIndex(headers,patterns);row[i>=0&&i<15?i:fallback]=value??'';};put([/معرف.*الرسالة/,/message.*id/,/^id$/],0,m.id||'');put([/التاريخوالوقت/,/التاريخ/,/date/],1,date);put([/^البند$/, /item/],2,String(g[0]||''));put([/التصنيف/,/الموازنة/],3,guideBudget(g));put([/المبلغ/,/amount/],4,amount??'');put([/الطرف/,/الوصف/,/merchant/,/description/],5,subject||snippet.slice(0,240));put([/نوعالعملية/,/الحركة/,/type/],6,movement);put([/قناةالعملية/,/القناة/,/channel/],7,detected);put([/^البنك$/, /الحساب/,/bank/,/account/],8,[bank,account].filter(Boolean).join(' ')||'غير محدد');put([/النظام/],9,String(g[2]||''));put([/حالةالتسجيل/,/الحالة/],10,status);put([/تاريخالإدخال/],11,new Date().toISOString());put([/^الفئة$/],12,String(g[9]||''));put([/^الفترة$/],13,String(g[10]||''));put([/^الصنف$/, /النطاق/],14,String(g[11]||''));return{row,status};}
async function syncClassifiedOperations(env:Env,labelLimit=2,perLabel=4){const token=await accessToken(env),ops=await readOperations(env,token),guide=await readSheet(env,token,'دليل البنود','A:L'),idIx=headerIndex(ops.headers,[/معرف.*الرسالة/,/message.*id/,/^id$/]),existingIds=new Set(ops.rows.map(r=>String(r[idIx>=0?idIx:0]||'').trim()).filter(Boolean));const active=guide.rows.map((r,i)=>({r,row:i+2,label:String(r[6]||'').trim(),last:String(r[8]||'').trim(),active:String(r[5]||'').trim().toLowerCase()})).filter(x=>x.label&&!/^(لا|no|false|0)$/.test(x.active)).sort((a,b)=>{const ta=Date.parse(a.last)||0,tb=Date.parse(b.last)||0;return ta-tb||a.row-b.row;}).slice(0,Math.max(1,Math.min(labelLimit,2))),rows:Row[]=[];let scanned=0,skipped=0,review=0;const syncedRows:number[]=[];for(const item of active){const list:any=await gmailListByLabel(token,item.label,Math.max(1,Math.min(perLabel,4))),refs=(list.messages||[]).filter((x:any)=>x.id).slice(0,Math.max(1,Math.min(perLabel,4)));scanned+=refs.length;for(const ref of refs){const id=String(ref.id||'');if(!id||existingIds.has(id))continue;const m=await gmailMessage(token,id);const financialLabels=(m.labelIds||[]).filter(label=>guide.rows.some(r=>String(r[6]||'').trim()===label));if(financialLabels.length!==1||financialLabels[0]!==item.label){skipped++;continue;}const built=buildOperationRow(ops.headers,item.r,m);rows.push(built.row);existingIds.add(id);if(built.status==='يحتاج مراجعة')review++;}syncedRows.push(item.row);}await appendOperationRows(env,token,rows);await updateGuideSync(env,token,syncedRows);return{ok:true,labelsChecked:active.length,scanned,added:rows.length,skipped,review,items:active.map(x=>String(x.r[0]||''))};}
async function reconcileAccounts(env:Env,limit=3){const token=await accessToken(env),{headers,rows}=await readOperations(env,token),idIx=headerIndex(headers,[/معرف.*الرسالة/,/message.*id/,/^id$/]),accountIx=headerIndex(headers,[/^البنك$/,/الحساب/,/bank/,/account/]);if(idIx<0||accountIx<0)return{ok:false,processed:0,updated:0,remaining:0,error:'تعذر تحديد عمود معرف الرسالة أو الحساب'};const candidates=rows.map((row,index)=>({index,id:String(row[idIx]||'').trim(),current:String(row[accountIx]||'').trim()})).filter(x=>x.id&&!currentAccountIsComplete(x.current)),batch=candidates.slice(0,Math.max(1,Math.min(limit,3))),updates:Array<{range:string;values:string[][]}>=[];let processed=0,updated=0,unresolved=0;for(const x of batch){processed++;try{const m=await gmailMessage(token,x.id),from=headerValue(m,'From'),subject=headerValue(m,'Subject'),snippet=(m.snippet||'').replace(/\s+/g,' ').trim(),combined=`${from}\n${subject}\n${snippet}`,bank=detectBankName(combined),account=extractAccountNumber(combined,bank);if(!bank||!account){unresolved++;continue;}const value=`${bank} ${account}`;if(value===x.current)continue;updates.push({range:`'العمليات'!${colName(accountIx)}${x.index+2}`,values:[[value]]});updated++;}catch{unresolved++;}}if(updates.length)await googleJson(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values:batchUpdate`,token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({valueInputOption:'USER_ENTERED',data:updates})});return{ok:true,processed,updated,unresolved,remaining:Math.max(candidates.length-batch.length,0),complete:candidates.length<=batch.length};}
async function authorized(request:Request,env:Env){const u=new URL(request.url);u.pathname='/auth/status';const r=await base.fetch(new Request(u.toString(),{method:'GET',headers:request.headers}),env),d:any=await r.json().catch(()=>({}));return Boolean(d?.authenticated);}

export default{async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);if(request.method==='OPTIONS')return base.fetch(request,env);
  if(url.pathname==='/api/operations'&&request.method==='GET'){if(!(await authorized(request,env)))return Response.json({ok:false,error:'Unauthorized'},{status:401,headers:cors(env)});let sync:any={ok:false,skipped:true};try{sync=await syncClassifiedOperations(env,2,4);}catch(e:any){sync={ok:false,error:e?.message||String(e)};}try{return Response.json({...await operationResponse(env),sync},{headers:cors(env)});}catch(e:any){return Response.json({ok:false,error:e?.message||String(e),sync},{status:500,headers:cors(env)});}}
  if(url.pathname==='/api/operations/sync'&&request.method==='POST'){if(!(await authorized(request,env)))return Response.json({ok:false,error:'Unauthorized'},{status:401,headers:cors(env)});try{const body:any=await request.json().catch(()=>({}));return Response.json(await syncClassifiedOperations(env,Math.min(Number(body?.labelLimit)||2,2),Math.min(Number(body?.perLabel)||4,4)),{headers:cors(env)});}catch(e:any){return Response.json({ok:false,error:e?.message||String(e)},{status:500,headers:cors(env)});}}
  if(url.pathname==='/api/operations/reconcile-accounts'&&request.method==='POST'){if(!(await authorized(request,env)))return Response.json({ok:false,error:'Unauthorized'},{status:401,headers:cors(env)});try{const body:any=await request.json().catch(()=>({}));return Response.json(await reconcileAccounts(env,Math.min(Number(body?.limit)||3,3)),{headers:cors(env)});}catch(e:any){return Response.json({ok:false,error:e?.message||String(e)},{status:500,headers:cors(env)});}}
  return base.fetch(request,env);
}};
