import current from './router20';
import type { Env } from './index';
type Row=unknown[];
function cors(env:Env){return{'Access-Control-Allow-Origin':env.FRONTEND_ORIGIN||'https://m14901507-boop.github.io','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Credentials':'true','Vary':'Origin'};}
function json(x:unknown,env:Env,s=200){return Response.json(x,{status:s,headers:cors(env)});}
function txt(v:unknown){return String(v??'').trim();}
async function auth(req:Request,env:Env){const u=new URL(req.url);u.pathname='/auth/status';const r=await current.fetch(new Request(u.toString(),{headers:req.headers}),env);const d:any=await r.json().catch(()=>({}));return !!d?.authenticated;}
async function token(env:Env){const b=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID.trim(),client_secret:env.GOOGLE_CLIENT_SECRET.trim(),refresh_token:env.GOOGLE_REFRESH_TOKEN.trim(),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b});const d:any=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth ${r.status}`);return String(d.access_token);}
async function gj(url:string,t:string){const r=await fetch(url,{headers:{Authorization:`Bearer ${t}`,Accept:'application/json'}});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);return d;}
async function readOps(env:Env,t:string){const rg=encodeURIComponent("'العمليات'!A:T");const d:any=await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`,t);const v:Row[]=d.values||[];return{headers:v[0]||[],rows:v.slice(1)};}
function parseTs(v:unknown){const s=txt(v);let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})(?:[ T](\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);if(m)return new Date(+m[3],+m[2]-1,+m[1],+(m[4]||0),+(m[5]||0),+(m[6]||0)).getTime();const d=new Date(s);return Number.isFinite(d.getTime())?d.getTime():0;}
function meta(key:string){if(key==='AHLI_001')return{bankName:'بنك الأهلي',accountNumber:'001'};if(key==='AHLI_002')return{bankName:'بنك الأهلي',accountNumber:'002'};if(key==='MEETHAQ_21')return{bankName:'ميثاق',accountNumber:'0021'};if(key==='MEETHAQ_22')return{bankName:'ميثاق',accountNumber:'0022'};if(key==='SOHAR_7010')return{bankName:'بنك صحار',accountNumber:'7010'};if(key==='SOHAR_7240')return{bankName:'بنك صحار',accountNumber:'7240'};if(key.startsWith('DHOFAR'))return{bankName:'بنك ظفار',accountNumber:key.split('_').slice(1).join('_')||'—'};return null;}
async function sheetBalances(env:Env){const t=await token(env),ops=await readOps(env,t),m=new Map<string,any>();for(const r of ops.rows){const key=txt(r[15]),bal=Number(r[17]),date=txt(r[19]),md=meta(key);if(!md||!Number.isFinite(bal)||!date)continue;const ts=parseTs(date),old=m.get(key);if(!old||ts>old.ts)m.set(key,{...md,accountKey:key,balance:bal,date,ts,messageId:txt(r[0])});}return{ok:true,source:'Google Sheets — العمليات P:R:T',count:m.size,balances:[...m.values()].map(({ts,...x})=>x)};}
export default{async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url);if(request.method==='OPTIONS')return current.fetch(request,env);try{
 if(u.pathname==='/api/gmail/latest-balances'&&request.method==='GET'){if(!(await auth(request,env)))return json({ok:false,error:'Unauthorized'},env,401);return json(await sheetBalances(env),env);}
 if(u.pathname==='/api/gmail/recent-bank-messages'&&request.method==='GET'){if(!(await auth(request,env)))return json({ok:false,error:'Unauthorized'},env,401);return json({ok:true,source:'Google Sheets only',messages:[],count:0},env);}
 return current.fetch(request,env);
}catch(e:any){return json({ok:false,error:e?.message||String(e)},env,500);}}};