import current from './router8';
import type { Env } from './index';

type Row=unknown[];
type GmailHeader={name?:string;value?:string};
type GmailMessage={id?:string;snippet?:string;internalDate?:string;labelIds?:string[];payload?:{headers?:GmailHeader[]}};
const FINANCIAL_BUDGETS=new Set(['عائلي شهري','عائلي سنوي','شخصي شهري','شخصي سنوي','تأمين المصروف','تأمين الدخل','الادخار والاستثمار']);
function cors(env:Env){return{'Access-Control-Allow-Origin':env.FRONTEND_ORIGIN||'https://m14901507-boop.github.io','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Credentials':'true','Vary':'Origin'};}
function json(data:unknown,env:Env,status=200){return Response.json(data,{status,headers:cors(env)});}
function clean(v:unknown){return String(v??'').trim().toLowerCase().replace(/[\s_\-]+/g,'');}
function hidx(headers:Row,patterns:RegExp[]){for(let i=0;i<headers.length;i++){const x=clean(headers[i]);if(patterns.some(p=>p.test(x)))return i;}return-1;}
function hv(m:GmailMessage,name:string){return(m.payload?.headers||[]).find(x=>(x.name||'').toLowerCase()===name.toLowerCase())?.value||'';}
async function authorized(request:Request,env:Env){const u=new URL(request.url);u.pathname='/auth/status';const r=await current.fetch(new Request(u.toString(),{method:'GET',headers:request.headers}),env);const d:any=await r.json().catch(()=>({}));return Boolean(d?.authenticated);}
async function token(env:Env){const body=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID.trim(),client_secret:env.GOOGLE_CLIENT_SECRET.trim(),refresh_token:env.GOOGLE_REFRESH_TOKEN.trim(),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d:any=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth ${r.status}`);return String(d.access_token);}
async function gj(url:string,t:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${t}`,Accept:'application/json',...(init.headers||{})}});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);return d;}
async function sheet(env:Env,t:string,name:string,part:string){const rg=encodeURIComponent(`'${name}'!${part}`);const d:any=await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`,t);const v:Row[]=d.values||[];return{headers:v[0]||[],rows:v.slice(1)};}
async function message(t:string,id:string){return gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`,t) as Promise<GmailMessage>;}
function bank(text:string){const s=text.toLowerCase();if(/ahli|الأهلي|الاهلي/.test(s))return'بنك الأهلي';if(/meethaq|ميثاق/.test(s))return'ميثاق';if(/dhofar|ظفار/.test(s))return'بنك ظفار';if(/sohar|صحار/.test(s))return'بنك صحار';if(/nizwa|نزوى/.test(s))return'بنك نزوى';if(/bank muscat|bankmuscat|بنك مسقط/.test(s))return'بنك مسقط';if(/oman arab bank|\boab\b|عمان العربي/.test(s))return'بنك عمان العربي';if(/national bank of oman|\bnbo\b|الوطني العماني/.test(s))return'البنك الوطني العماني';if(/alizz|العز/.test(s))return'بنك العز الإسلامي';return'';}
function normalizeAccount(b:string,no:string){let n=String(no||'').replace(/\D/g,'');if(b==='بنك الأهلي'){if(['1','01','001'].includes(n))return'001';if(['2','02','002'].includes(n))return'002';return'';}if(b==='ميثاق'&&['21','021','0021'].includes(n))return'0021';return n;}
function account(text:string,b=''){if(/0108\s*[#*xX]{4,}\s*001\b/i.test(text))return'001';if(/0108\s*[#*xX]{4,}\s*002\b/i.test(text))return'002';const cs:string[]=[];for(const p of[/(?:account|acct|a\/?c)(?:\s*(?:no|number|ending|ending\s+in))?[^0-9#*xX]{0,24}[#*xX-]*(\d{1,4})\b/ig,/[#*xX]{2,}(\d{1,4})\b/g,/\b\d{2,8}[#*xX-]{2,}(\d{1,4})\b/g]){let m:RegExpExecArray|null;while((m=p.exec(text))!==null)if(m[1])cs.push(m[1]);}return normalizeAccount(b,cs[0]||'');}
function amount(text:string){for(const p of[/(?:OMR|RO|O\.?R\.?)\s*([0-9][0-9,]*(?:\.[0-9]{1,3})?)/i,/([0-9][0-9,]*(?:\.[0-9]{1,3})?)\s*(?:OMR|RO|O\.?R\.?)/i]){const m=text.match(p);if(m?.[1])return Number(m[1].replace(/,/g,''));}return null;}
function opType(text:string){if(/POS Purchase|Debit Card.*utili[sz]ed|purchase/i.test(text))return'مصروف/شراء بالبطاقة';if(/\bcredited\b/i.test(text))return'دخل/تحويل وارد';if(/\bdebited\b/i.test(text))return'مصروف/تحويل صادر';if(/\b(withdrawal|withdrawn|ATM)\b/i.test(text))return'مصروف/سحب نقدي';return'غير محدد';}
function movement(v:string){if(/دخل|وارد|credited/i.test(v))return'دخل';if(/مصروف|صادر|debited|purchase|withdraw/i.test(v))return'مصروف';if(/تحويل/i.test(v))return'تحويل';return v||'غير محدد';}
function guideBudget(r:Row){const x=String(r[1]||'').trim();if(FINANCIAL_BUDGETS.has(x))return x;const p=String(r[10]||''),s=String(r[11]||'');if(s.includes('عائلي')&&p.includes('شهري'))return'عائلي شهري';if(s.includes('عائلي')&&p.includes('سنوي'))return'عائلي سنوي';if(s.includes('شخصي')&&p.includes('شهري'))return'شخصي شهري';if(s.includes('شخصي')&&p.includes('سنوي'))return'شخصي سنوي';return x||'غير مصنف';}
function isFinancial(r:Row){const budget=guideBudget(r),system=String(r[2]||'').toLowerCase(),mv=String(r[3]||'').toLowerCase(),all=[r[1],r[2],r[3],r[4],r[9],r[10],r[11]].map(x=>String(x||'')).join(' ').toLowerCase();if(/غير\s*مالي|non.?financial|أمان|الامان|تسجيل\s*الدخول/.test(system+' '+mv+' '+all))return false;if(/تحويل\s*داخلي|تحويلات\s*داخلية|internal.?transfer/.test(all))return false;return FINANCIAL_BUDGETS.has(budget)&&Boolean(String(r[0]||'').trim());}
function build(headers:Row,g:Row,m:GmailMessage){const from=hv(m,'From'),subject=hv(m,'Subject'),snippet=(m.snippet||'').replace(/\s+/g,' ').trim(),text=`${from}\n${subject}\n${snippet}`,b=bank(text),a=account(text,b),amt=amount(text),raw=hv(m,'Date')||(m.internalDate?new Date(Number(m.internalDate)).toISOString():new Date().toISOString()),pd=new Date(raw),date=!isNaN(pd.getTime())?pd.toISOString():raw,det=opType(text),mov=movement(String(g[3]||'').trim()||det),status=(b&&a&&amt!=null)?'مسجل تلقائيا من Gmail':'يحتاج مراجعة',row=new Array(15).fill('');const put=(ps:RegExp[],fallback:number,v:unknown)=>{const i=hidx(headers,ps);row[i>=0&&i<15?i:fallback]=v??'';};put([/معرف.*الرسالة/,/message.*id/,/^id$/],0,m.id||'');put([/التاريخوالوقت/,/التاريخ/,/date/],1,date);put([/^البند$/, /item/],2,String(g[0]||''));put([/التصنيف/,/الموازنة/],3,guideBudget(g));put([/المبلغ/,/amount/],4,amt??'');put([/الطرف/,/الوصف/,/merchant/,/description/],5,subject||snippet.slice(0,240));put([/نوعالعملية/,/الحركة/,/type/],6,mov);put([/قناةالعملية/,/القناة/,/channel/],7,det);put([/^البنك$/, /الحساب/,/bank/,/account/],8,[b,a].filter(Boolean).join(' ')||'غير محدد');put([/النظام/],9,String(g[2]||''));put([/حالةالتسجيل/,/الحالة/],10,status);put([/تاريخالإدخال/],11,new Date().toISOString());put([/^الفئة$/],12,String(g[9]||''));put([/^الفترة$/],13,String(g[10]||''));put([/^الصنف$/, /النطاق/],14,String(g[11]||''));return row;}
async function updateSync(env:Env,t:string,rows:number[]){if(!rows.length)return;const stamp=new Date().toISOString(),data=rows.flatMap(r=>[{range:`'دليل البنود'!H${r}`,values:[['تمت المزامنة']]},{range:`'دليل البنود'!I${r}`,values:[[stamp]]}]);await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values:batchUpdate`,t,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({valueInputOption:'USER_ENTERED',data})});}
async function syncAndRead(env:Env){const t=await token(env),ops=await sheet(env,t,'العمليات','A:O'),guide=await sheet(env,t,'دليل البنود','A:L'),idIx=hidx(ops.headers,[/معرف.*الرسالة/,/message.*id/,/^id$/]),existing=new Set(ops.rows.map(r=>String(r[idIx>=0?idIx:0]||'').trim()).filter(Boolean));const candidates=guide.rows.map((r,i)=>({r,row:i+2,label:String(r[6]||'').trim(),last:String(r[8]||'').trim(),active:String(r[5]||'').trim().toLowerCase()})).filter(x=>x.label&&isFinancial(x.r)&&!/^(لا|no|false|0)$/.test(x.active)).sort((a,b)=>(Date.parse(a.last)||0)-(Date.parse(b.last)||0)||a.row-b.row).slice(0,3);const add:Row[]=[];let listed=0,missingFound=0;const touched:number[]=[];for(const c of candidates){const list:any=await gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages?labelIds=${encodeURIComponent(c.label)}&maxResults=50`,t);const ids=(list.messages||[]).map((x:any)=>String(x.id||'')).filter(Boolean);listed+=ids.length;const missing=ids.filter((id:string)=>!existing.has(id)).slice(0,Math.max(0,6-add.length));missingFound+=missing.length;for(const id of missing){const m=await message(t,id);const financialLabels=(m.labelIds||[]).filter(l=>guide.rows.some(r=>String(r[6]||'').trim()===l&&isFinancial(r)));if(financialLabels.length!==1||financialLabels[0]!==c.label)continue;add.push(build(ops.headers,c.r,m));existing.add(id);if(add.length>=6)break;}touched.push(c.row);if(add.length>=6)break;}if(add.length){const rg=encodeURIComponent("'العمليات'!A:O");await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,t,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values:add})});}await updateSync(env,t,touched);const updated=add.length?await sheet(env,t,'العمليات','A:O'):ops;const itemIx=hidx(updated.headers,[/^البند$/, /item/]),budgetIx=hidx(updated.headers,[/التصنيف/,/الموازنة/]);const validItems=new Set(guide.rows.filter(isFinancial).map(r=>String(r[0]||'').trim()));const visible=updated.rows.filter(r=>{const item=String(r[itemIx>=0?itemIx:2]||'').trim(),budget=String(r[budgetIx>=0?budgetIx:3]||'').trim();return validItems.has(item)&&FINANCIAL_BUDGETS.has(budget);});return{ok:true,sheet:'العمليات',headers:updated.headers,rows:visible,sheetRowCount:updated.rows.length,rowCount:visible.length,liveCount:0,sync:{labelsChecked:candidates.length,messagesListed:listed,missingFound,added:add.length,items:candidates.map(x=>String(x.r[0]||''))}};}
export default{async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url);if(request.method==='OPTIONS')return current.fetch(request,env);try{if(u.pathname==='/api/operations'&&request.method==='GET'){if(!(await authorized(request,env)))return json({ok:false,error:'Unauthorized'},env,401);return json(await syncAndRead(env),env);}return current.fetch(request,env);}catch(e:any){return json({ok:false,error:e?.message||String(e)},env,500);}}};
