import current from './router13';
import type { Env } from './index';

type Row=unknown[];
type GmailHeader={name?:string;value?:string};
type GmailMessage={id?:string;snippet?:string;internalDate?:string;labelIds?:string[];payload?:{headers?:GmailHeader[]}};
const FINANCIAL_BUDGETS=new Set(['عائلي شهري','عائلي سنوي','شخصي شهري','شخصي سنوي','تأمين المصروف','تأمين الدخل','الادخار والاستثمار']);
function cors(env:Env){return{'Access-Control-Allow-Origin':env.FRONTEND_ORIGIN||'https://m14901507-boop.github.io','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Credentials':'true','Vary':'Origin'};}
function json(data:unknown,env:Env,status=200){return Response.json(data,{status,headers:cors(env)});}
function clean(v:unknown){return String(v??'').trim().toLowerCase().replace(/[\s_\-]+/g,'');}
function hidx(headers:Row,patterns:RegExp[]){for(let i=0;i<headers.length;i++){const x=clean(headers[i]);if(patterns.some(p=>p.test(x)))return i;}return-1;}
function hv(m:GmailMessage,name:string){return(m.payload?.headers||[]).find(x=>(x.name||'').toLowerCase()===name.toLowerCase())?.value||'';}
async function authorized(request:Request,env:Env){const u=new URL(request.url);u.pathname='/auth/status';const r=await current.fetch(new Request(u.toString(),{method:'GET',headers:request.headers}),env);const d:any=await r.json().catch(()=>({}));return Boolean(d?.authenticated);}
async function token(env:Env){const body=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID.trim(),client_secret:env.GOOGLE_CLIENT_SECRET.trim(),refresh_token:env.GOOGLE_REFRESH_TOKEN.trim(),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d:any=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth ${r.status}`);return String(d.access_token);}
async function gj(url:string,t:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${t}`,Accept:'application/json',...(init.headers||{})}});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);return d;}
async function sheet(env:Env,t:string,name:string,part:string){const rg=encodeURIComponent(`'${name}'!${part}`);const d:any=await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`,t);const v:Row[]=d.values||[];return{headers:v[0]||[],rows:v.slice(1)};}
async function message(t:string,id:string){return gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`,t) as Promise<GmailMessage>;}
function bank(text:string){const s=text.toLowerCase();if(/ahli|الأهلي|الاهلي/.test(s))return'بنك الأهلي';if(/meethaq|ميثاق/.test(s))return'ميثاق';if(/dhofar|ظفار/.test(s))return'بنك ظفار';if(/sohar|صحار/.test(s))return'بنك صحار';return'';}
function normalizeAccount(b:string,no:string){let n=String(no||'').replace(/\D/g,'');if(b==='بنك الأهلي'){if(['1','01','001'].includes(n))return'001';if(['2','02','002'].includes(n))return'002';return'';}if(b==='ميثاق'){if(['21','021','0021'].includes(n))return'0021';if(['22','022','0022'].includes(n))return'0022';}return n;}
function account(text:string,b=''){if(/0108\s*[#*xX]{4,}\s*001\b/i.test(text))return'001';if(/0108\s*[#*xX]{4,}\s*002\b/i.test(text))return'002';const cs:string[]=[];for(const p of[/(?:account|acct|a\/?c)(?:\s*(?:no|number|ending|ending\s+in))?[^0-9#*xX]{0,24}[#*xX-]*(\d{1,4})\b/ig,/[#*xX]{2,}(\d{1,4})\b/g]){let m:RegExpExecArray|null;while((m=p.exec(text))!==null)if(m[1])cs.push(m[1]);}return normalizeAccount(b,cs[0]||'');}
function amount(text:string){for(const p of[/(?:OMR|RO|O\.?R\.?)\s*([0-9][0-9,]*(?:\.[0-9]{1,3})?)/i,/([0-9][0-9,]*(?:\.[0-9]{1,3})?)\s*(?:OMR|RO|O\.?R\.?)/i]){const m=text.match(p);if(m?.[1])return Number(m[1].replace(/,/g,''));}return null;}
function opType(text:string){if(/POS Purchase|Debit Card.*utili[sz]ed|purchase/i.test(text))return'مصروف/شراء بالبطاقة';if(/\bcredited\b/i.test(text))return'دخل/تحويل وارد';if(/\bdebited\b/i.test(text))return'مصروف/تحويل صادر';if(/\b(withdrawal|withdrawn|ATM)\b/i.test(text))return'مصروف/سحب نقدي';return'غير محدد';}
function guideBudget(r:Row){const x=String(r[1]||'').trim();return FINANCIAL_BUDGETS.has(x)?x:'';}
function isFinancial(r:Row){const budget=guideBudget(r),all=[r[1],r[2],r[3],r[4],r[9],r[10],r[11]].map(x=>String(x||'')).join(' ').toLowerCase();if(!budget)return false;if(/غير\s*مالي|non.?financial|أمان|الامان|تسجيل\s*الدخول/.test(all))return false;if(/تحويل\s*داخلي|تحويلات\s*داخلية|internal.?transfer/.test(all))return false;return Boolean(String(r[0]||'').trim());}
function buildPatch(headers:Row,g:Row,m:GmailMessage,existing?:Row){const row=(existing?[...existing]:new Array(15).fill('')).slice(0,15);while(row.length<15)row.push('');const from=hv(m,'From'),subject=hv(m,'Subject'),snippet=(m.snippet||'').replace(/\s+/g,' ').trim(),text=`${from}\n${subject}\n${snippet}`,b=bank(text),a=account(text,b),amt=amount(text),raw=hv(m,'Date')||(m.internalDate?new Date(Number(m.internalDate)).toISOString():new Date().toISOString()),pd=new Date(raw),date=!isNaN(pd.getTime())?pd.toISOString():raw,det=opType(text),put=(ps:RegExp[],fallback:number,v:unknown)=>{const i=hidx(headers,ps);row[i>=0&&i<15?i:fallback]=v??'';};put([/معرف.*الرسالة/,/message.*id/,/^id$/],0,m.id||'');put([/التاريخوالوقت/,/التاريخ/,/date/],1,date);put([/^البند$/, /item/],2,String(g[0]||''));put([/التصنيف/,/الموازنة/],3,guideBudget(g));if(amt!=null)put([/المبلغ/,/amount/],4,amt);if(!existing)put([/الطرف/,/الوصف/,/merchant/,/description/],5,subject||snippet.slice(0,240));put([/نوعالعملية/,/الحركة/,/type/],6,String(g[3]||'').trim()||det);if(!existing)put([/قناةالعملية/,/القناة/,/channel/],7,det);if(!existing)put([/^البنك$/, /الحساب/,/bank/,/account/],8,[b,a].filter(Boolean).join(' ')||'غير محدد');put([/النظام/],9,String(g[2]||''));put([/حالةالتسجيل/,/الحالة/],10,'مسجل تلقائيا من Gmail');if(!existing)put([/تاريخالإدخال/],11,new Date().toISOString());put([/^الفئة$/],12,String(g[9]||''));put([/^الفترة$/],13,String(g[10]||''));put([/^الصنف$/, /النطاق/],14,String(g[11]||''));return row;}
function clearClassification(headers:Row,row:Row){const out=[...row].slice(0,15);while(out.length<15)out.push('');const put=(ps:RegExp[],fallback:number,v:unknown)=>{const i=hidx(headers,ps);out[i>=0&&i<15?i:fallback]=v??'';};put([/^البند$/, /item/],2,'');put([/التصنيف/,/الموازنة/],3,'');put([/النظام/],9,'');put([/حالةالتسجيل/,/الحالة/],10,'بدون تصنيف بند في Gmail');put([/^الفئة$/],12,'');put([/^الفترة$/],13,'');put([/^الصنف$/, /النطاق/],14,'');return out;}
async function reconcile(env:Env){const t=await token(env),ops=await sheet(env,t,'العمليات','A:O'),guide=await sheet(env,t,'دليل البنود','A:L'),idIx=hidx(ops.headers,[/معرف.*الرسالة/,/message.*id/,/^id$/]);const byLabel=new Map<string,Row>();for(const r of guide.rows){const label=String(r[6]||'').trim(),active=String(r[5]||'').trim().toLowerCase();if(label&&isFinancial(r)&&!/^(لا|no|false|0)$/.test(active))byLabel.set(label,r);}const byId=new Map<string,{row:Row,rowNumber:number}>();ops.rows.forEach((r,i)=>{const id=String(r[idIx>=0?idIx:0]||'').trim();if(id)byId.set(id,{row:r,rowNumber:i+2});});const list:any=await gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent('newer_than:30d')}&maxResults=24`,t);const ids=(list.messages||[]).map((x:any)=>String(x.id||'')).filter(Boolean);const append:Row[]=[],updates:Array<{range:string;values:unknown[][]}>=[];let inspected=0,added=0,updated=0,cleared=0;
 for(const id of ids.slice(0,20)){const m=await message(t,id);inspected++;const financialLabels=(m.labelIds||[]).filter(l=>byLabel.has(l));const ex=byId.get(id);if(financialLabels.length===1){const g=byLabel.get(financialLabels[0])!;const patched=buildPatch(ops.headers,g,m,ex?.row);if(ex){if(JSON.stringify(patched)!==JSON.stringify(ex.row.slice(0,15))){updates.push({range:`'العمليات'!A${ex.rowNumber}:O${ex.rowNumber}`,values:[patched]});updated++;}}else{append.push(patched);added++;}}else if(ex){const clearedRow=clearClassification(ops.headers,ex.row);if(JSON.stringify(clearedRow)!==JSON.stringify(ex.row.slice(0,15))){updates.push({range:`'العمليات'!A${ex.rowNumber}:O${ex.rowNumber}`,values:[clearedRow]});cleared++;}}}
 if(updates.length)await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values:batchUpdate`,t,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({valueInputOption:'USER_ENTERED',data:updates})});
 if(append.length){const rg=encodeURIComponent("'العمليات'!A:O");await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,t,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values:append})});}
 return{ok:true,source:'Gmail current labels ↔ Google Sheets',inspected,added,updated,cleared};}
export default{async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url);if(request.method==='OPTIONS')return current.fetch(request,env);try{if(u.pathname==='/api/sync/operations'&&request.method==='POST'){if(!(await authorized(request,env)))return json({ok:false,error:'Unauthorized'},env,401);return json(await reconcile(env),env);}return current.fetch(request,env);}catch(e:any){return json({ok:false,error:e?.message||String(e)},env,500);}}};
