import current from './router6';
import type { Env } from './index';

type Row=unknown[];
type GmailHeader={name?:string;value?:string};
type GmailMessage={id?:string;snippet?:string;internalDate?:string;labelIds?:string[];payload?:{headers?:GmailHeader[]}};

function cors(env:Env){return{'Access-Control-Allow-Origin':env.FRONTEND_ORIGIN||'https://m14901507-boop.github.io','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Credentials':'true','Vary':'Origin'};}
function json(data:unknown,env:Env,status=200){return Response.json(data,{status,headers:cors(env)});}
function clean(v:unknown){return String(v??'').trim().toLowerCase().replace(/[\s_\-]+/g,'');}
function hidx(headers:Row,patterns:RegExp[]){for(let i=0;i<headers.length;i++){const x=clean(headers[i]);if(patterns.some(p=>p.test(x)))return i;}return-1;}
function hv(m:GmailMessage,name:string){return(m.payload?.headers||[]).find(x=>(x.name||'').toLowerCase()===name.toLowerCase())?.value||'';}
async function authorized(request:Request,env:Env){const u=new URL(request.url);u.pathname='/auth/status';const r=await current.fetch(new Request(u.toString(),{method:'GET',headers:request.headers}),env);const d:any=await r.json().catch(()=>({}));return Boolean(d?.authenticated);}
async function token(env:Env){const body=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID.trim(),client_secret:env.GOOGLE_CLIENT_SECRET.trim(),refresh_token:env.GOOGLE_REFRESH_TOKEN.trim(),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d:any=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth ${r.status}`);return String(d.access_token);}
async function gj(url:string,t:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${t}`,Accept:'application/json',...(init.headers||{})}});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);return d;}
async function sheet(env:Env,t:string,name:string,part:string){const rg=encodeURIComponent(`'${name}'!${part}`);const d:any=await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`,t);const v:Row[]=d.values||[];return{headers:v[0]||[],rows:v.slice(1)};}
async function message(t:string,id:string){return gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`,t) as Promise<GmailMessage>;}
function bank(text:string){const s=text.toLowerCase();if(/ahli|الأهلي|الاهلي/.test(s))return'بنك الأهلي';if(/meethaq|ميثاق/.test(s))return'ميثاق';if(/dhofar|ظفار/.test(s))return'بنك ظفار';if(/sohar|صحار/.test(s))return'بنك صحار';if(/nizwa|نزوى/.test(s))return'بنك نزوى';if(/bank muscat|bankmuscat|بنك مسقط/.test(s))return'بنك مسقط';if(/oman arab bank|\boab\b|عمان العربي/.test(s))return'بنك عمان العربي';if(/national bank of oman|\bnbo\b|الوطني العماني/.test(s))return'البنك الوطني العماني';if(/alizz|العز/.test(s))return'بنك العز الإسلامي';return'';}
function normalizeAccount(b:string,no:string){let n=String(no||'').replace(/\D/g,'');if(b==='بنك الأهلي'){if(['1','01','001'].includes(n))return'001';if(['2','02','002'].includes(n))return'002';return'';}if(b==='ميثاق'&&['21','021','0021'].includes(n))return'0021';return n;}
function account(text:string,b=''){if(/0108\s*[#*xX]{4,}\s*001\b/i.test(text))return'001';if(/0108\s*[#*xX]{4,}\s*002\b/i.test(text))return'002';const cs:string[]=[];for(const p of[/(?:account|acct|a\/?c)(?:\s*(?:no|number|ending|ending\s+in))?[^0-9#*xX]{0,24}[#*xX-]*(\d{1,4})\b/ig,/[#*xX]{2,}(\d{1,4})\b/g,/\b\d{2,8}[#*xX-]{2,}(\d{1,4})\b/g]){let m:RegExpExecArray|null;while((m=p.exec(text))!==null)if(m[1])cs.push(m[1]);}return normalizeAccount(b,cs[0]||'');}
function amount(text:string){for(const p of[/(?:OMR|RO|O\.?R\.?)\s*([0-9][0-9,]*(?:\.[0-9]{1,3})?)/i,/([0-9][0-9,]*(?:\.[0-9]{1,3})?)\s*(?:OMR|RO|O\.?R\.?)/i]){const m=text.match(p);if(m?.[1])return Number(m[1].replace(/,/g,''));}return null;}
function balance(text:string){for(const p of[/available\s*(?:balance|bal(?:ance)?)\s*(?:is|:|-)?\s*(?:OMR|RO|O\.?R\.?)?\s*([0-9][0-9,]*(?:\.[0-9]{1,3})?)/i,/(?:balance|bal(?:ance)?)\s*(?:is|:|-)\s*(?:OMR|RO|O\.?R\.?)?\s*([0-9][0-9,]*(?:\.[0-9]{1,3})?)/i]){const m=text.match(p);if(m?.[1])return Number(m[1].replace(/,/g,''));}return null;}
function opType(text:string){if(/POS Purchase|Debit Card.*utili[sz]ed|purchase/i.test(text))return'مصروف/شراء بالبطاقة';if(/\bcredited\b/i.test(text))return'دخل/تحويل وارد';if(/\bdebited\b/i.test(text))return'مصروف/تحويل صادر';if(/\b(withdrawal|withdrawn|ATM)\b/i.test(text))return'مصروف/سحب نقدي';return'غير محدد';}
function movement(v:string){if(/دخل|وارد|credited/i.test(v))return'دخل';if(/مصروف|صادر|debited|purchase|withdraw/i.test(v))return'مصروف';if(/تحويل/i.test(v))return'تحويل';return v||'غير محدد';}
function guideBudget(r:Row){const x=String(r[1]||'').trim(),known=['عائلي شهري','عائلي سنوي','شخصي شهري','شخصي سنوي','تأمين المصروف','تأمين الدخل','الادخار والاستثمار'];if(known.includes(x))return x;const p=String(r[10]||''),s=String(r[11]||'');if(s.includes('عائلي')&&p.includes('شهري'))return'عائلي شهري';if(s.includes('عائلي')&&p.includes('سنوي'))return'عائلي سنوي';if(s.includes('شخصي')&&p.includes('شهري'))return'شخصي شهري';if(s.includes('شخصي')&&p.includes('سنوي'))return'شخصي سنوي';return x||'غير مصنف';}
function build(headers:Row,g:Row,m:GmailMessage){const from=hv(m,'From'),subject=hv(m,'Subject'),snippet=(m.snippet||'').replace(/\s+/g,' ').trim(),text=`${from}\n${subject}\n${snippet}`,b=bank(text),a=account(text,b),amt=amount(text),raw=hv(m,'Date')||(m.internalDate?new Date(Number(m.internalDate)).toISOString():new Date().toISOString()),pd=new Date(raw),date=!isNaN(pd.getTime())?pd.toISOString():raw,det=opType(text),mov=movement(String(g[3]||'').trim()||det),status=(b&&a&&amt!=null)?'مسجل تلقائيا من Gmail':'يحتاج مراجعة',row=new Array(15).fill('');const put=(ps:RegExp[],fallback:number,v:unknown)=>{const i=hidx(headers,ps);row[i>=0&&i<15?i:fallback]=v??'';};put([/معرف.*الرسالة/,/message.*id/,/^id$/],0,m.id||'');put([/التاريخوالوقت/,/التاريخ/,/date/],1,date);put([/^البند$/, /item/],2,String(g[0]||''));put([/التصنيف/,/الموازنة/],3,guideBudget(g));put([/المبلغ/,/amount/],4,amt??'');put([/الطرف/,/الوصف/,/merchant/,/description/],5,subject||snippet.slice(0,240));put([/نوعالعملية/,/الحركة/,/type/],6,mov);put([/قناةالعملية/,/القناة/,/channel/],7,det);put([/^البنك$/, /الحساب/,/bank/,/account/],8,[b,a].filter(Boolean).join(' ')||'غير محدد');put([/النظام/],9,String(g[2]||''));put([/حالةالتسجيل/,/الحالة/],10,status);put([/تاريخالإدخال/],11,new Date().toISOString());put([/^الفئة$/],12,String(g[9]||''));put([/^الفترة$/],13,String(g[10]||''));put([/^الصنف$/, /النطاق/],14,String(g[11]||''));return row;}
async function fastSync(env:Env){const t=await token(env),ops=await sheet(env,t,'العمليات','A:O'),guide=await sheet(env,t,'دليل البنود','A:L'),idIx=hidx(ops.headers,[/معرف.*الرسالة/,/message.*id/,/^id$/]),existing=new Set(ops.rows.map(r=>String(r[idIx>=0?idIx:0]||'').trim()).filter(Boolean)),byLabel=new Map<string,Row>();for(const r of guide.rows){const id=String(r[6]||'').trim(),active=String(r[5]||'').trim().toLowerCase();if(id&&!/^(لا|no|false|0)$/.test(active))byLabel.set(id,r);}const list:any=await gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent('newer_than:7d has:userlabels')}&maxResults=20`,t),refs=(list.messages||[]).filter((x:any)=>x.id).slice(0,12);const rows:Row[]=[];let checked=0,classified=0;for(const ref of refs){const id=String(ref.id||'');if(!id||existing.has(id))continue;checked++;const m=await message(t,id);const labels=(m.labelIds||[]).filter(x=>byLabel.has(x));if(labels.length!==1)continue;classified++;rows.push(build(ops.headers,byLabel.get(labels[0]) as Row,m));existing.add(id);}if(rows.length){const rg=encodeURIComponent("'العمليات'!A:O");await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,t,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values:rows})});}const updated=rows.length?await sheet(env,t,'العمليات','A:O'):ops;return{ok:true,sheet:'العمليات',headers:updated.headers,rows:updated.rows,sheetRowCount:updated.rows.length,rowCount:updated.rows.length,liveCount:0,sync:{recentChecked:checked,classified,added:rows.length}};}
async function latestBalances(env:Env){const t=await token(env);const q='newer_than:30d {"available balance" balance}';const list:any=await gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(q)}&maxResults=20`,t);const refs=(list.messages||[]).filter((x:any)=>x.id).slice(0,12),map=new Map<string,any>();for(const ref of refs){const m=await message(t,String(ref.id)),from=hv(m,'From'),subject=hv(m,'Subject'),snippet=(m.snippet||'').replace(/\s+/g,' ').trim(),text=`${from}\n${subject}\n${snippet}`,b=bank(text),a=account(text,b),bal=balance(text);if(!b||!a||bal==null)continue;const raw=hv(m,'Date')||(m.internalDate?new Date(Number(m.internalDate)).toISOString():''),ts=new Date(raw).getTime()||0,key=`${b}|${a}`,old=map.get(key);if(!old||ts>old.ts)map.set(key,{bankName:b,accountNumber:a,balance:bal,date:raw,messageId:m.id,ts});}return{ok:true,balances:[...map.values()].map(({ts,...x})=>x),count:map.size};}

export default{async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url);if(request.method==='OPTIONS')return current.fetch(request,env);try{if(u.pathname==='/api/operations'&&request.method==='GET'){if(!(await authorized(request,env)))return json({ok:false,error:'Unauthorized'},env,401);return json(await fastSync(env),env);}if(u.pathname==='/api/gmail/latest-balances'&&request.method==='GET'){if(!(await authorized(request,env)))return json({ok:false,error:'Unauthorized'},env,401);return json(await latestBalances(env),env);}return current.fetch(request,env);}catch(e:any){return json({ok:false,error:e?.message||String(e)},env,500);}}};
