import current from './router4';
import type { Env } from './index';

const RENTALS='الإيجارات';
const RECEIPTS='إيصالات الإيجارات';
const RENTAL_HEADERS=['معرف المستأجر','اسم المستأجر','البريد الإلكتروني','الوحدة','الإيجار الشهري','يوم الاستحقاق','الحالة','آخر تاريخ استلام','آخر مبلغ مستلم','رمز الرابط','نشط','ملاحظات','تاريخ الإنشاء','آخر تحديث'];
const RECEIPT_HEADERS=['معرف الإيصال','معرف المستأجر','تاريخ الاستلام','المبلغ','ملاحظات','مرجع العملية','تاريخ الإرسال','حالة الإرسال','تاريخ الإنشاء'];

function cors(env:Env){return{
  'Access-Control-Allow-Origin':env.FRONTEND_ORIGIN||'https://m14901507-boop.github.io',
  'Access-Control-Allow-Headers':'Content-Type,Authorization',
  'Access-Control-Allow-Methods':'GET,POST,OPTIONS',
  'Access-Control-Allow-Credentials':'true','Vary':'Origin'
};}
function json(data:unknown,env:Env,status=200){return Response.json(data,{status,headers:cors(env)});}
async function authorized(request:Request,env:Env){const u=new URL(request.url);u.pathname='/auth/status';const r=await current.fetch(new Request(u.toString(),{method:'GET',headers:request.headers}),env);const d:any=await r.json().catch(()=>({}));return Boolean(d?.authenticated);}
async function accessToken(env:Env){const body=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID.trim(),client_secret:env.GOOGLE_CLIENT_SECRET.trim(),refresh_token:env.GOOGLE_REFRESH_TOKEN.trim(),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d:any=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth ${r.status}`);return String(d.access_token);}
async function gjson(url:string,token:string,opt:RequestInit={}){const r=await fetch(url,{...opt,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})}});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);return d;}
function range(sheet:string,part:string){return encodeURIComponent(`'${sheet}'!${part}`);}
async function readSheet(env:Env,token:string,sheet:string,part='A:Z'){const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${range(sheet,part)}?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`;const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}});if(r.status===400||r.status===404)return null;const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);const v=d.values||[];return{headers:v[0]||[],rows:v.slice(1)};}
async function ensureSheet(env:Env,token:string,sheet:string,headers:string[]){let found=await readSheet(env,token,sheet,'A1:Z2');if(found)return;await gjson(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}:batchUpdate`,token,{method:'POST',body:JSON.stringify({requests:[{addSheet:{properties:{title:sheet}}}]})});await appendRows(env,token,sheet,[headers]);}
async function appendRows(env:Env,token:string,sheet:string,rows:any[][]){const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${range(sheet,'A:Z')}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`;return gjson(url,token,{method:'POST',body:JSON.stringify({majorDimension:'ROWS',values:rows})});}
async function updateRow(env:Env,token:string,sheet:string,row:number,values:any[]){const rg=`'${sheet}'!A${row}:N${row}`;const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${encodeURIComponent(rg)}?valueInputOption=USER_ENTERED`;return gjson(url,token,{method:'PUT',body:JSON.stringify({range:rg,majorDimension:'ROWS',values:[values]})});}
function uid(prefix:string){return `${prefix}_${crypto.randomUUID().replace(/-/g,'')}`;}
function clean(v:any){return String(v??'').trim();}
function validEmail(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);}
function rentalObject(r:any[],row:number){return{row,tenantId:clean(r[0]),name:clean(r[1]),email:clean(r[2]),unit:clean(r[3]),monthlyRent:Number(r[4])||0,dueDay:Number(r[5])||0,status:clean(r[6])||'نشط',lastReceiptDate:clean(r[7]),lastReceiptAmount:Number(r[8])||0,publicToken:clean(r[9]),active:String(r[10]??'TRUE').toLowerCase()!=='false',notes:clean(r[11]),createdAt:clean(r[12]),updatedAt:clean(r[13])};}
async function listRentals(env:Env,token:string){await ensureSheet(env,token,RENTALS,RENTAL_HEADERS);const d=await readSheet(env,token,RENTALS,'A:N');return(d?.rows||[]).map((r:any[],i:number)=>rentalObject(r,i+2)).filter((x:any)=>x.tenantId);}
async function listReceipts(env:Env,token:string){await ensureSheet(env,token,RECEIPTS,RECEIPT_HEADERS);const d=await readSheet(env,token,RECEIPTS,'A:I');return(d?.rows||[]).map((r:any[],i:number)=>({row:i+2,receiptId:clean(r[0]),tenantId:clean(r[1]),date:clean(r[2]),amount:Number(r[3])||0,notes:clean(r[4]),operationRef:clean(r[5]),sentAt:clean(r[6]),sendStatus:clean(r[7]),createdAt:clean(r[8])})).filter((x:any)=>x.receiptId);}
async function upsertRental(env:Env,p:any){const token=await accessToken(env);const rentals=await listRentals(env,token);const id=clean(p.tenantId)||uid('TEN');const existing=rentals.find((x:any)=>x.tenantId===id);const email=clean(p.email);if(email&&!validEmail(email))throw new Error('صيغة البريد الإلكتروني غير صحيحة');const now=new Date().toISOString();const publicToken=existing?.publicToken||uid('PUB');const values=[id,clean(p.name)||existing?.name||'',email||existing?.email||'',clean(p.unit)||existing?.unit||'',Number(p.monthlyRent??existing?.monthlyRent)||0,Number(p.dueDay??existing?.dueDay)||0,clean(p.status)||existing?.status||'نشط',existing?.lastReceiptDate||'',existing?.lastReceiptAmount||0,publicToken,p.active===false?'FALSE':'TRUE',clean(p.notes)||existing?.notes||'',existing?.createdAt||now,now];if(existing)await updateRow(env,token,RENTALS,existing.row,values);else await appendRows(env,token,RENTALS,[values]);return{ok:true,tenant:rentalObject(values,existing?.row||rentals.length+2)};}
function b64url(s:string){const bytes=new TextEncoder().encode(s);let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
async function gmailSend(token:string,to:string,subject:string,html:string){const raw=[`To: ${to}`,'MIME-Version: 1.0','Content-Type: text/html; charset=UTF-8',`Subject: =?UTF-8?B?${btoa(unescape(encodeURIComponent(subject)))}?=`,'',html].join('\r\n');const r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({raw:b64url(raw)})});const d:any=await r.json().catch(()=>({}));if(!r.ok){const msg=d?.error?.message||`Gmail API ${r.status}`;if(r.status===403)throw new Error('صلاحية Gmail للإرسال غير مفعلة. يلزم تفويض gmail.send مرة واحدة.');throw new Error(msg);}return d;}
async function addReceipt(env:Env,p:any){const token=await accessToken(env);const rentals=await listRentals(env,token);const tenant=rentals.find((x:any)=>x.tenantId===clean(p.tenantId));if(!tenant)throw new Error('المستأجر غير موجود');const amount=Number(p.amount);if(!(amount>0))throw new Error('قيمة الاستلام غير صحيحة');const date=clean(p.date)||new Date().toISOString().slice(0,10);const now=new Date().toISOString(),receiptId=uid('REC');let sentAt='',sendStatus='لم يرسل';const publicUrl=`https://m14901507-boop.github.io/26/preview/tenant.html?t=${encodeURIComponent(tenant.publicToken)}`;if(p.sendEmail){if(!tenant.email)throw new Error('لا يوجد بريد إلكتروني محفوظ لهذا المستأجر');const html=`<div dir="rtl" style="font-family:Arial,sans-serif;line-height:1.8"><h2>شكرًا لك، ${tenant.name||'مستأجرنا الكريم'}</h2><p>تم استلام مبلغ الإيجار بقيمة <b>${amount.toFixed(3)} ر.ع</b> بتاريخ <b>${date}</b> للوحدة <b>${tenant.unit||'—'}</b>.</p><p>نشكر لكم تعاونكم والتزامكم.</p><p><a href="${publicUrl}">عرض صفحة الإيجار والإيصالات</a></p><p style="color:#666;font-size:12px">FLOOSY — إدارة الإيجارات</p></div>`;await gmailSend(token,tenant.email,'إيصال استلام الإيجار — FLOOSY',html);sentAt=now;sendStatus='تم الإرسال';}
await ensureSheet(env,token,RECEIPTS,RECEIPT_HEADERS);await appendRows(env,token,RECEIPTS,[[receiptId,tenant.tenantId,date,amount,clean(p.notes),clean(p.operationRef),sentAt,sendStatus,now]]);const values=[tenant.tenantId,tenant.name,tenant.email,tenant.unit,tenant.monthlyRent,tenant.dueDay,tenant.status,date,amount,tenant.publicToken,tenant.active?'TRUE':'FALSE',tenant.notes,tenant.createdAt,now];await updateRow(env,token,RENTALS,tenant.row,values);return{ok:true,receipt:{receiptId,tenantId:tenant.tenantId,date,amount,notes:clean(p.notes),sentAt,sendStatus},publicUrl};}
async function publicRental(env:Env,tokenValue:string){if(!tokenValue||tokenValue.length<20)throw new Error('الرابط غير صالح');const token=await accessToken(env);const rentals=await listRentals(env,token);const tenant=rentals.find((x:any)=>x.publicToken===tokenValue&&x.active);if(!tenant)throw new Error('الرابط غير صالح أو غير نشط');const receipts=(await listReceipts(env,token)).filter((x:any)=>x.tenantId===tenant.tenantId).sort((a:any,b:any)=>String(b.date).localeCompare(String(a.date)));return{ok:true,tenant:{name:tenant.name,unit:tenant.unit,monthlyRent:tenant.monthlyRent,dueDay:tenant.dueDay,status:tenant.status},receipts};}

export default{async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);if(request.method==='OPTIONS')return current.fetch(request,env);try{
  if(url.pathname==='/public/rental'&&request.method==='GET')return json(await publicRental(env,url.searchParams.get('t')||''),env);
  if(url.pathname.startsWith('/api/rentals')){if(!(await authorized(request,env)))return json({ok:false,error:'Unauthorized'},env,401);
    const token=await accessToken(env);
    if(url.pathname==='/api/rentals'&&request.method==='GET')return json({ok:true,rentals:await listRentals(env,token),receipts:await listReceipts(env,token)},env);
    if(url.pathname==='/api/rentals/upsert'&&request.method==='POST')return json(await upsertRental(env,await request.json().catch(()=>({}))),env);
    if(url.pathname==='/api/rentals/receipt'&&request.method==='POST')return json(await addReceipt(env,await request.json().catch(()=>({}))),env);
  }
  return current.fetch(request,env);
}catch(e:any){return json({ok:false,error:e?.message||String(e)},env,500);}}};
