import current from './router17';
import type { Env } from './index';
type Row=unknown[];
type Msg={id?:string;labelIds?:string[];payload?:{headers?:Array<{name?:string;value?:string}>}};
const BUDGETS=new Set(['عائلي شهري','عائلي سنوي','شخصي شهري','شخصي سنوي','تأمين المصروف','تأمين الدخل','الادخار والاستثمار']);
function cors(env:Env){return{'Access-Control-Allow-Origin':env.FRONTEND_ORIGIN||'https://m14901507-boop.github.io','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Credentials':'true','Vary':'Origin'};}
function json(x:unknown,env:Env,s=200){return Response.json(x,{status:s,headers:cors(env)});}
function txt(v:unknown){return String(v??'').trim();}
async function auth(req:Request,env:Env){const u=new URL(req.url);u.pathname='/auth/status';const r=await current.fetch(new Request(u.toString(),{headers:req.headers}),env);const d:any=await r.json().catch(()=>({}));return !!d?.authenticated;}
async function token(env:Env){const b=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID.trim(),client_secret:env.GOOGLE_CLIENT_SECRET.trim(),refresh_token:env.GOOGLE_REFRESH_TOKEN.trim(),grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b});const d:any=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth ${r.status}`);return String(d.access_token);}
async function gj(url:string,t:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${t}`,Accept:'application/json',...(init.headers||{})}});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Google API ${r.status}`);return d;}
async function read(env:Env,t:string,name:string,range:string){const rg=encodeURIComponent(`'${name}'!${range}`);const d:any=await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values/${rg}?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`,t);const v:Row[]=d.values||[];return{rows:v.slice(1)};}
async function batch(env:Env,t:string,data:Array<{range:string;values:unknown[][]}>){if(!data.length)return;await gj(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.SPREADSHEET_ID.trim())}/values:batchUpdate`,t,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({valueInputOption:'USER_ENTERED',data})});}
function usable(g:Row){const active=txt(g[5]).toLowerCase(),all=[g[1],g[2],g[3],g[4]].map(txt).join(' ');return !!txt(g[0])&&!!txt(g[6])&&!/^(لا|no|false|0|غير نشط)$/.test(active)&&!/غير\s*مالي|أمان|الامان|تسجيل\s*الدخول/i.test(all);}
function apply(op:Row,g:Row){const r=[...op];while(r.length<15)r.push('');r[2]=txt(g[0]);r[3]=BUDGETS.has(txt(g[1]))?txt(g[1]):'';r[6]=txt(g[3])||r[6];r[9]=txt(g[2]);r[10]='تمت استعادة التصنيف من Gmail';r[12]=txt(g[9]);r[13]=txt(g[10]);r[14]=txt(g[11]);return r;}
async function msg(t:string,id:string){return gj(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=metadata`,t) as Promise<Msg>;}
async function restoreMissing(env:Env){const t=await token(env),guide=await read(env,t,'دليل البنود','A:L'),ops=await read(env,t,'العمليات','A:O'),byLabel=new Map<string,Row>();for(const g of guide.rows)if(usable(g))byLabel.set(txt(g[6]),g);const candidates=ops.rows.map((r,i)=>({r,n:i+2,id:txt(r[0])})).filter(x=>x.id&&(!txt(x.r[2])||!txt(x.r[3]))).slice(-8).reverse(),writes:Array<{range:string;values:unknown[][]}>=[];let restored=0,checked=0,ambiguous=0;for(const c of candidates){const m=await msg(t,c.id);checked++;const matches=(m.labelIds||[]).map(l=>byLabel.get(l)).filter(Boolean) as Row[];if(matches.length===1){writes.push({range:`'العمليات'!A${c.n}:O${c.n}`,values:[apply(c.r,matches[0])]});restored++;}else if(matches.length>1)ambiguous++;}await batch(env,t,writes);return{checked,restored,ambiguous};}
export default{async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url);if(request.method==='OPTIONS')return current.fetch(request,env);try{if(u.pathname==='/api/sync/operations'&&request.method==='POST'){if(!(await auth(request,env)))return json({ok:false,error:'Unauthorized'},env,401);const restore=await restoreMissing(env);const baseResp=await current.fetch(request.clone(),env);const base:any=await baseResp.json().catch(()=>({}));if(!baseResp.ok)return json(base,env,baseResp.status);return json({...base,restored:restore.restored,restoreChecked:restore.checked,restoreAmbiguous:restore.ambiguous},env);}return current.fetch(request,env);}catch(e:any){return json({ok:false,error:e?.message||String(e)},env,500);}}};
