(()=>{
  if(window.__floosyAssociationTabsV2)return;window.__floosyAssociationTabsV2=true;
  const $=id=>document.getElementById(id),money=v=>Number(v||0).toLocaleString('en-US',{minimumFractionDigits:3,maximumFractionDigits:3})+' ر.ع';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const addMonths=(v,n)=>{const m=/^(\d{4})-(\d{2})(?:-(\d{2}))?/.exec(String(v||''));if(!m)return'';const d=new Date(Date.UTC(+m[1],+m[2]-1,+(m[3]||1)));d.setUTCMonth(d.getUTCMonth()+Math.max(0,Number(n)||0));return d.toISOString().slice(0,10)};
  const fmt=v=>{if(!v)return'—';const d=new Date(String(v).length===7?v+'-01':v);return isNaN(d)?String(v):d.toLocaleDateString('ar-OM',{year:'numeric',month:'short',day:String(v).length>7?'numeric':undefined})};
  const getData=()=>{try{return typeof DATA!=='undefined'&&DATA?DATA:{associations:[],members:[],payments:[]}}catch(e){return{associations:[],members:[],payments:[]}}};
  const selectedId=()=>String($('associationSelect')?.value||'');
  let active='overview',timer=0;

  function style(){if($('associationTabsStyleV2'))return;const s=document.createElement('style');s.id='associationTabsStyleV2';s.textContent=`
  .assoc2-nav{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:10px 0 13px;padding:8px;border:1px solid #2d435a;border-radius:16px;background:linear-gradient(145deg,#0f1822,#090f16)}.assoc2-tabs{display:flex;gap:7px;flex-wrap:wrap}.assoc2-tab{min-height:40px;padding:0 15px;border:1px solid #30455c;border-radius:11px;background:#0b131c;color:#aebdcd;font-weight:800;cursor:pointer}.assoc2-tab.active{color:#fff;border-color:#168df2;background:linear-gradient(135deg,#168df2,#075fbf);box-shadow:0 7px 22px rgba(22,141,242,.18)}.assoc2-current{display:flex;align-items:center;gap:8px;min-width:300px}.assoc2-current span{font-size:9px;color:#879aaf;white-space:nowrap}.assoc2-current .control{min-width:190px}.assoc2-view{display:none}.assoc2-view.active{display:block;animation:assoc2Fade .2s ease}@keyframes assoc2Fade{from{opacity:.35;transform:translateY(4px)}to{opacity:1;transform:none}}
  .assoc2-tools,.assoc2-listhead{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:12px;padding:12px;border:1px solid #273b50;border-radius:15px;background:#0a1119}.assoc2-tools .group,.assoc2-listhead .group{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.assoc2-tools .control{min-width:190px}.assoc2-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:11px}.assoc2-card{padding:14px;border:1px solid #2c4158;border-radius:17px;background:linear-gradient(145deg,#101a25,#080e15);transition:.18s ease;position:relative;overflow:hidden}.assoc2-card:before{content:"";position:absolute;inset:0 auto auto 0;width:45%;height:2px;background:linear-gradient(90deg,#168df2,#27d391,transparent)}.assoc2-card.selected{border-color:#168df2;box-shadow:0 0 0 1px rgba(22,141,242,.18),0 18px 36px rgba(0,0,0,.2)}.assoc2-card:hover{transform:translateY(-2px)}.assoc2-head{display:flex;justify-content:space-between;gap:9px;align-items:flex-start}.assoc2-head h3{margin:0;font-size:16px}.assoc2-head small{display:block;margin-top:4px;color:#8498ad}.assoc2-badge{padding:5px 8px;border-radius:999px;border:1px solid rgba(39,211,145,.35);color:#63eab7;font-size:9px;white-space:nowrap}.assoc2-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.assoc2-kpi{padding:8px;border:1px solid rgba(255,255,255,.07);border-radius:10px;background:rgba(255,255,255,.018)}.assoc2-kpi span{display:block;color:#7f92a7;font-size:8px}.assoc2-kpi b{display:block;margin-top:4px;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.assoc2-actions{display:flex;gap:7px;flex-wrap:wrap;padding-top:10px;border-top:1px solid #223244}.assoc2-empty{padding:30px;text-align:center;color:#8ca0b5;border:1px dashed #30455c;border-radius:16px;background:#091018}.assoc2-oldtoolbar{display:none!important}
  @media(max-width:760px){.assoc2-nav{align-items:stretch;flex-direction:column}.assoc2-current{min-width:0;width:100%}.assoc2-current .control{flex:1;min-width:0}.assoc2-tools{align-items:stretch;flex-direction:column}.assoc2-tools .group{display:grid;grid-template-columns:1fr}.assoc2-tools .control{width:100%;min-width:0}.assoc2-kpis{grid-template-columns:1fr 1fr}}
  `;document.head.appendChild(s)}

  function drawAssociations(){const grid=$('assoc2Grid');if(!grid)return;const d=getData(),arr=Array.isArray(d.associations)?d.associations:[],sel=selectedId();let html='';if(!arr.length)html='<div class="assoc2-empty">لا توجد جمعية مسجلة بعد. اضغط «+ إضافة جمعية» لإنشاء أول جمعية.</div>';else html=arr.map(a=>{const id=String(a.associationId||''),ms=(d.members||[]).filter(m=>String(m.associationId)===id&&m.active!==false),ps=(d.payments||[]).filter(p=>String(p.associationId)===id),paid=ps.reduce((s,p)=>s+Number(p.amount||0),0),planned=Number(a.plannedMembers||0)||ms.length,end=a.endDate||addMonths(a.startMonth,a.durationMonths);return `<article class="assoc2-card ${id===sel?'selected':''}"><div class="assoc2-head"><div><h3>${esc(a.name||'جمعية')}</h3><small>${planned} عضو مخطط • ${ms.length} عضو مضاف</small></div><span class="assoc2-badge">الدور كل ${Math.max(1,Number(a.payoutEveryMonths||1))} أشهر</span></div><div class="assoc2-kpis"><div class="assoc2-kpi"><span>المساهمة / عضو</span><b>${money(a.contributionAmount)}</b></div><div class="assoc2-kpi"><span>مدة الجمعية</span><b>${Number(a.durationMonths||0)} شهر</b></div><div class="assoc2-kpi"><span>إجمالي الدفعات</span><b>${money(paid)}</b></div><div class="assoc2-kpi"><span>تاريخ البدء</span><b>${fmt(a.startMonth)}</b></div><div class="assoc2-kpi"><span>تاريخ الانتهاء</span><b>${fmt(end)}</b></div><div class="assoc2-kpi"><span>عمليات الدفع</span><b>${ps.length}</b></div></div><div class="assoc2-actions"><button class="btn sm primary" data-a2="open" data-id="${esc(id)}">فتح</button><button class="btn sm" data-a2="edit" data-id="${esc(id)}">تعديل</button><button class="btn sm red" data-a2="delete" data-id="${esc(id)}">حذف</button></div></article>`}).join('');if(grid.innerHTML!==html)grid.innerHTML=html}

  function show(tab){active=tab;document.querySelectorAll('.assoc2-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.assoc2-view').forEach(v=>v.classList.toggle('active',v.dataset.view===tab));if(tab==='associations')drawAssociations();setTimeout(()=>window.parent?.postMessage({type:'floosy-association-updated'},location.origin),20)}
  function choose(id){const s=$('associationSelect');if(!s)return;s.value=id;s.dispatchEvent(new Event('change',{bubbles:true}))}
  function refreshLater(){clearTimeout(timer);timer=setTimeout(()=>{drawAssociations()},80)}

  function init(){if($('assoc2Nav'))return true;const status=$('status'),toolbar=document.querySelector('.toolbar'),hero=document.querySelector('.hero'),charts=document.querySelector('.charts'),editor=$('memberEditor'),head=document.querySelector('.sectionHead'),cards=$('memberCards'),detail=$('memberDetail'),settings=$('associationForm')?.closest('details.panel'),assocSelect=$('associationSelect'),memberFilter=$('memberFilter'),memberSearch=$('memberSearch'),addMember=$('addMember'),newAssociation=$('newAssociation');if(!status||!toolbar||!hero||!charts||!cards||!assocSelect)return false;style();toolbar.classList.add('assoc2-oldtoolbar');
    const nav=document.createElement('div');nav.id='assoc2Nav';nav.className='assoc2-nav';nav.innerHTML='<div class="assoc2-tabs"><button type="button" class="assoc2-tab active" data-tab="overview">الرئيسية / لوحة العرض</button><button type="button" class="assoc2-tab" data-tab="members">قائمة الأعضاء</button><button type="button" class="assoc2-tab" data-tab="associations">قائمة الجمعيات</button></div><div class="assoc2-current"><span>الجمعية الحالية</span><div id="assoc2SelectMount"></div></div>';status.after(nav);$('assoc2SelectMount').appendChild(assocSelect);
    const overview=document.createElement('section');overview.className='assoc2-view active';overview.dataset.view='overview';nav.after(overview);overview.append(hero,charts);
    const members=document.createElement('section');members.className='assoc2-view';members.dataset.view='members';overview.after(members);const tools=document.createElement('div');tools.className='assoc2-tools';tools.innerHTML='<div class="group" id="assoc2MemberFilters"></div><div class="group" id="assoc2MemberActions"></div>';members.appendChild(tools);if(memberFilter)$('assoc2MemberFilters').appendChild(memberFilter);if(memberSearch)$('assoc2MemberFilters').appendChild(memberSearch);if(addMember)$('assoc2MemberActions').appendChild(addMember);if(editor)members.appendChild(editor);if(head)members.appendChild(head);members.appendChild(cards);if(detail)members.appendChild(detail);
    const list=document.createElement('section');list.className='assoc2-view';list.dataset.view='associations';members.after(list);const listHead=document.createElement('div');listHead.className='assoc2-listhead';listHead.innerHTML='<div><b>قائمة الجمعيات</b><div style="color:#8296aa;font-size:9px;margin-top:4px">إضافة جمعية جديدة أو فتح وتعديل الجمعية الحالية مع مؤشرات سريعة.</div></div><div class="group" id="assoc2ListActions"></div>';list.appendChild(listHead);if(newAssociation)$('assoc2ListActions').appendChild(newAssociation);const grid=document.createElement('div');grid.id='assoc2Grid';grid.className='assoc2-grid';list.appendChild(grid);if(settings)list.appendChild(settings);
    nav.onclick=e=>{const b=e.target.closest('.assoc2-tab');if(b)show(b.dataset.tab)};grid.onclick=e=>{const b=e.target.closest('[data-a2]');if(!b)return;choose(b.dataset.id);setTimeout(()=>{if(b.dataset.a2==='open')show('overview');else if(b.dataset.a2==='edit'){show('associations');if(settings)settings.open=true;if(typeof window.__floosyAssociationEdit==='function')window.__floosyAssociationEdit()}else if(b.dataset.a2==='delete'&&typeof window.__floosyAssociationDelete==='function')window.__floosyAssociationDelete()},50)};
    assocSelect.addEventListener('change',refreshLater);document.addEventListener('click',e=>{if(e.target.closest('#newAssociation'))setTimeout(()=>show('associations'),0);if(e.target.closest('#addMember'))setTimeout(()=>show('members'),0)});const st=$('status');if(st)new MutationObserver(refreshLater).observe(st,{subtree:true,childList:true,characterData:true});drawAssociations();show('overview');return true}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{let n=0,t=setInterval(()=>{if(init()||++n>40)clearInterval(t)},100)});else{let n=0,t=setInterval(()=>{if(init()||++n>40)clearInterval(t)},100)}
})();
